---
ansible_user: root
agent_init_args: >-
  --server https://{{ apiserver_endpoint }}:6443 --token {{ hostvars[groups['controller'][0]]['token'] | default(k3s_token) }}
  {% if cni_native != 'none' %} 
  --flannel-iface={{ cni_iface }} 
  {% endif %}
  {{ extra_agent_args | default("") }}
