---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: prereq

- hosts: balancer
  become: yes
  roles:
    - role: balancer

- hosts: k8s_cluster
  become: yes
  roles:
    - role: download

- hosts: controller
  become: yes
  roles:
    - role: k3s/controller

- hosts: worker
  become: yes
  roles:
    - role: k3s/worker