---
- hosts: all
  gather_facts: yes
  become: true
  roles:
    - role: prereq

- hosts: balancer
  become: true
  roles:
    - role: balancer

- hosts: k8s_cluster
  become: true
  roles:
    - role: download

- hosts: controller
  become: true
  roles:
    - role: k3s/controller

- hosts: controller
  become: true
  roles:
    - role: k3s/cni
      when: cni_native == "none" and cni_plugin != "none" 

- hosts: worker
  become: true
  roles:
    - role: k3s/worker
