---
#- name: Enable cgroup via boot commandline if not already enabled for Ubuntu 
#  lineinfile:
#    path: /boot/cmdline.txt
#    backrefs: yes
#    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
#    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
#  notify: reboot

- name: Disable swap
  become: yes
  shell: >
    sudo swapoff -v /swap.img
    sudo rm /swap.img
  when: ansible_swaptotal_mb > 0

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
    state: present

- name: Install iptables
  apt:
    name: iptables
    state: present

- name: Flush iptables before changing to iptables-legacy
  iptables:
    flush: true
  changed_when: false   # iptables flush always returns changed

- name: Ensure iptables tooling does not use the nftables backend
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Ensure ip6tables tooling does not use the nftables backend
  alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy
