---
ansible_user: root
server_init_args: >-
  --tls-san {{ apiserver_endpoint }} --cluster-cidr {{podsubnet}}
  {% if cni_native != 'none' %}
  --flannel-backend={{ cni_native }} --flannel-iface={{ cni_iface }}
  {% else %}
  --flannel-backend={{ cni_native }} --disable-network-policy
  {% endif %}
  {% if groups['controller'] | length > 1 %}
  {% if ansible_hostname == hostvars[groups['controller'][0]]['ansible_hostname'] %}
  --cluster-init
  {% else %}
  --server https://{{ apiserver_endpoint }}:6443
  {% endif %} --token {{ k3s_token }}
  {% endif %} 
  {{ extra_server_args | default('') }}
