---
ansible_user: root
server_init_args: >-
  {% if groups['controller'] | length > 1 %}
    {% if ansible_hostname == hostvars[groups['controller'][0]]['ansible_hostname'] %}
      --cluster-init
    {% else %}
      --server https://{{ apiserver_endpoint }}:6443
    {% endif %}
    --token {{ k3s_token }}
  {% endif %}
  {{ extra_server_args | default('') }}
