---
apiVersion: v1
kind: Service
metadata:
  name: pihole-headless
  namespace: baselab
  labels:
    run: pihole-sts
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    run: pihole-sts


